# Generated by Django 6.0.3 on 2026-03-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=100, verbose_name='Китайское слово')),
                ('pinyin', models.CharField(max_length=100, verbose_name='Пиньинь')),
                ('translation', models.CharField(max_length=200, verbose_name='Перевод')),
                ('example', models.TextField(blank=True, verbose_name='Пример')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='Тема')),
                ('hsk_level', models.PositiveSmallIntegerField(default=1, verbose_name='Уровень HSK')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
